//! Generated by easymock

#include "mock_em_header_2.h"
#include <stdlib.h>
#include <string.h>
#include <assert.h>

//!
//! Mock for em_open
//!

static easymock_param easymock_meta_params_of_em_open[] =
{
    {
        .index = 1,
        .name = "file",
        .type = "const char*",
        .type_basic = "char*",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_open,
            file),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_open,
            file),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    },
    {
        .index = 2,
        .name = "oflag",
        .type = "int",
        .type_basic = "int",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_open,
            oflag),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_open,
            oflag),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    }
};

static easymock_params_of_em_open*
easymock_create_params_of_em_open()
{
    easymock_params_of_em_open* _em_p = NULL;
    _em_p = malloc(sizeof(easymock_params_of_em_open));
    memset(_em_p, 0, sizeof(easymock_params_of_em_open));
    return _em_p;
}

static void easymock_destroy_params_of_em_open(
    void* _em_params)
{
    easymock_params_of_em_open* _em_p = _em_params;
    if (_em_p->_em_va_formatted) {
        free(_em_p->_em_va_formatted);
    }
    va_end(_em_p->_em_va_list);
    free(_em_p);
}

static void easymock_assign_params_of_em_open(
    easymock_params_of_em_open* _em_params,
    const char* file,
    int oflag)
{
    _em_params->file = (const char*)file;
    _em_params->oflag = (int)oflag;
}

static easymock_func easymock_meta_func_of_em_open =
{
    .name = "em_open",
    .params = easymock_meta_params_of_em_open,
    .params_size = EASYMOCK_SIZEOF_ARRAY(
        easymock_meta_params_of_em_open),
    .fn_destroy_params = easymock_destroy_params_of_em_open
};

easymock_func* easymock_meta_of_em_open()
{
    return &easymock_meta_func_of_em_open;
}

static easymock_result_of_em_open*
easymock_create_result_of_em_open()
{
    easymock_result_of_em_open* _em_result = NULL;
    _em_result = malloc(sizeof(easymock_result_of_em_open));
    memset(_em_result, 0, sizeof(easymock_result_of_em_open));
    return _em_result;
}

static void easymock_assign_result_of_em_open(
    easymock_result_of_em_open* _em_result,
    easymock_return_type_of_em_open _em_return_value)
{
    _em_result->return_value = _em_return_value;
}

static easymock_call_instance
easymock_static_call_instance_of_em_open;

static easymock_call_instance*
easymock_static_ptr_call_instance_of_em_open = NULL;

static easymock_params_of_em_open
easymock_static_params_expected_of_em_open;

static easymock_params_of_em_open
easymock_static_params_received_of_em_open;

static easymock_result_of_em_open
easymock_static_result_of_em_open;

static easymock_call_instance* easymock_new_static_em_open()
{
    easymock_call_instance* ci = NULL;
    memset(&easymock_static_call_instance_of_em_open, 0,
           sizeof(easymock_static_call_instance_of_em_open));
    memset(&easymock_static_params_expected_of_em_open, 0,
           sizeof(easymock_static_params_expected_of_em_open));
    memset(&easymock_static_params_received_of_em_open, 0,
           sizeof(easymock_static_params_received_of_em_open));
    ci = &easymock_static_call_instance_of_em_open;
    ci->params_expected =
        &easymock_static_params_expected_of_em_open;
    ci->params_received =
        &easymock_static_params_received_of_em_open;
    ci->result =
        &easymock_static_result_of_em_open;
    ci->func = &easymock_meta_func_of_em_open;
    return ci;
}

static easymock_call_instance* easymock_get_static_em_open()
{
    return easymock_static_ptr_call_instance_of_em_open;
}

static easymock_call_instance* easymock_new_em_open()
{
    easymock_call_instance* ci = NULL;
    if (easymock_is_started()) {
        ci = easymock_call_instance_create();
        ci->params_expected =
            easymock_create_params_of_em_open();
        ci->params_received =
            easymock_create_params_of_em_open();
        ci->result =
            easymock_create_result_of_em_open();
        ci->func = &easymock_meta_func_of_em_open;
        easymock_call_instance_push(ci);
    } else {
        ci = easymock_new_static_em_open();
        easymock_static_ptr_call_instance_of_em_open = ci;
    }
    return ci;
}

void easymock_ignore_and_return_em_open(
    easymock_return_type_of_em_open _em_return_value)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_IGNORE;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    easymock_assign_result_of_em_open(
        _em_ci->result, _em_return_value);
}

void easymock_ignore_and_callback_em_open(
    easymock_fn_callback_em_open _em_fn_callback,
    void* _em_arg_cb)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_IGNORE;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_callback = _em_arg_cb;
}

void easymock_match_va_and_return_em_open(
    easymock_return_type_of_em_open _em_return_value,
    const char* file,
    int oflag,
    ...)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_MATCH;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    easymock_assign_params_of_em_open(
        _em_ci->params_expected,
        file,
        oflag);
    easymock_assign_result_of_em_open(
        _em_ci->result, _em_return_value);
    {
        easymock_params_of_em_open* _em_p =
            (easymock_params_of_em_open*)
            _em_ci->params_expected;
        va_start(_em_p->_em_va_list, oflag);
    }
}

void easymock_match_va_and_callback_em_open(
    easymock_fn_callback_em_open _em_fn_callback,
    void* _em_arg_cb,
    const char* file,
    int oflag,
    ...)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_MATCH;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    easymock_assign_params_of_em_open(
        _em_ci->params_expected,
        file,
        oflag);
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_callback = _em_arg_cb;
    {
        easymock_params_of_em_open* _em_p =
            (easymock_params_of_em_open*)
            _em_ci->params_expected;
        va_start(_em_p->_em_va_list, oflag);
    }
}

void easymock_check_and_return_em_open(
    easymock_fn_check_em_open _em_fn_check,
    void* _em_arg_ch,
    easymock_return_type_of_em_open _em_return_value)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_CHECK;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    _em_ci->fn_check = _em_fn_check;
    _em_ci->arg_check = _em_arg_ch;
    easymock_assign_result_of_em_open(
        _em_ci->result, _em_return_value);
}

void easymock_check_and_callback_em_open(
    easymock_fn_check_em_open _em_fn_check,
    void* _em_arg_ch,
    easymock_fn_callback_em_open _em_fn_callback,
    void* _em_arg_cb)
{
    easymock_call_instance* _em_ci = easymock_new_em_open();
    _em_ci->prm_mode = EASYMOCK_PRM_CHECK;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    _em_ci->fn_check = _em_fn_check;
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_check = _em_arg_ch;
    _em_ci->arg_callback = _em_arg_cb;
}

int em_open(
    const char* file,
    int oflag,
    ...)
{
    static char _em_sparams[EASYMOCK_MSG_ERROR_LENGTH_MAX] =
        "    (no params)\n";

    easymock_call_instance* _em_ci = NULL;
    int _em_is_unexpected = 0;
    int _em_is_seq_call = 0;

    // 1) try to get a sequence-configured call instance
    _em_ci = easymock_call_instance_pop("em_open");
    if (_em_ci) {
        easymock_nb_seq_calls_inc();
        _em_is_seq_call = 1;
    } else {
        // 2) try to get a static-configured call instance
        _em_ci = easymock_get_static_em_open();
        if (_em_ci) {
            easymock_nb_stc_calls_inc();
        } else {
            // 3) get a dummy all-zero static call instance
            _em_ci = easymock_new_static_em_open();
            _em_is_unexpected = easymock_is_started();
        }
    }
    assert(_em_ci);

    easymock_assign_params_of_em_open(
        _em_ci->params_received,
        file,
        oflag);
    {
        easymock_params_of_em_open* _em_p =
            (easymock_params_of_em_open*)
            _em_ci->params_received;
        va_start(_em_p->_em_va_list, oflag);
    }

    if (_em_is_unexpected) {
        // print the received params
        easymock_call_instance_print_params(
            _em_ci, _em_sparams, sizeof(_em_sparams));

        easymock_error(
            "%s: Called - UNEXPECTED!\n%s", "em_open",
            _em_sparams);
    } else {
        if (_em_is_seq_call) {
            easymock_log("%s: Called - OK\n", "em_open");
        }

        // === match params
        if (_em_ci->prm_mode == EASYMOCK_PRM_MATCH) {
            easymock_call_instance_match_params(_em_ci);
        }
        // === check params
        else if (_em_ci->prm_mode == EASYMOCK_PRM_CHECK) {
            assert(_em_ci->fn_check);
            int _em_rc = ((easymock_fn_check_em_open)_em_ci->fn_check)(
                (easymock_params_of_em_open*)_em_ci->params_received,
                _em_ci->arg_check);
            easymock_call_instance_print_params(
                _em_ci, _em_sparams, sizeof(_em_sparams));
            if (_em_rc == 0) {
                easymock_log(
                    "%s: Check - OK\n%s",
                    "em_open", _em_sparams);
            } else {
                easymock_error(
                    "%s: Check - FAILED!\n%s",
                    "em_open", _em_sparams);
            }
        }
        // === call the provided callback
        if (_em_ci->act_mode == EASYMOCK_ACT_CALLBACK) {
            assert(_em_ci->fn_callback);
            return ((easymock_fn_callback_em_open)
                _em_ci->fn_callback)(
                    (easymock_params_of_em_open*)
                    _em_ci->params_received,
                    _em_ci->arg_callback);
        }
    }
    // === return the result
    return ((easymock_result_of_em_open*)
            _em_ci->result)->return_value;
}

//!
//! Mock for em_snprintf
//!

static easymock_param easymock_meta_params_of_em_snprintf[] =
{
    {
        .index = 1,
        .name = "str",
        .type = "char*",
        .type_basic = "char*",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_snprintf,
            str),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_snprintf,
            str),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    },
    {
        .index = 2,
        .name = "size",
        .type = "size_t",
        .type_basic = "long unsigned int",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_snprintf,
            size),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_snprintf,
            size),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    },
    {
        .index = 3,
        .name = "format",
        .type = "const char*",
        .type_basic = "char*",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_snprintf,
            format),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_snprintf,
            format),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    },
    {
        .index = 4,
        .name = "_em_va_formatted",
        .type = "char*",
        .type_basic = "char*",
        .offset = EASYMOCK_MEMBER_OFFSET(
            easymock_params_of_em_snprintf,
            _em_va_formatted),
        .size = EASYMOCK_MEMBER_SIZE(
            easymock_params_of_em_snprintf,
            _em_va_formatted),
        .fn_match = easymock_match_param_smart,
        .fn_print = easymock_print_param_smart,
    }
};

static easymock_params_of_em_snprintf*
easymock_create_params_of_em_snprintf()
{
    easymock_params_of_em_snprintf* _em_p = NULL;
    _em_p = malloc(sizeof(easymock_params_of_em_snprintf));
    memset(_em_p, 0, sizeof(easymock_params_of_em_snprintf));
    return _em_p;
}

static void easymock_destroy_params_of_em_snprintf(
    void* _em_params)
{
    easymock_params_of_em_snprintf* _em_p = _em_params;
    if (_em_p->_em_va_formatted) {
        free(_em_p->_em_va_formatted);
    }
    va_end(_em_p->_em_va_list);
    free(_em_p);
}

static void easymock_assign_params_of_em_snprintf(
    easymock_params_of_em_snprintf* _em_params,
    char* str,
    size_t size,
    const char* format)
{
    _em_params->str = (char*)str;
    _em_params->size = (size_t)size;
    _em_params->format = (const char*)format;
}

static easymock_func easymock_meta_func_of_em_snprintf =
{
    .name = "em_snprintf",
    .params = easymock_meta_params_of_em_snprintf,
    .params_size = EASYMOCK_SIZEOF_ARRAY(
        easymock_meta_params_of_em_snprintf),
    .fn_destroy_params = easymock_destroy_params_of_em_snprintf
};

easymock_func* easymock_meta_of_em_snprintf()
{
    return &easymock_meta_func_of_em_snprintf;
}

static easymock_result_of_em_snprintf*
easymock_create_result_of_em_snprintf()
{
    easymock_result_of_em_snprintf* _em_result = NULL;
    _em_result = malloc(sizeof(easymock_result_of_em_snprintf));
    memset(_em_result, 0, sizeof(easymock_result_of_em_snprintf));
    return _em_result;
}

static void easymock_assign_result_of_em_snprintf(
    easymock_result_of_em_snprintf* _em_result,
    easymock_return_type_of_em_snprintf _em_return_value)
{
    _em_result->return_value = _em_return_value;
}

static easymock_call_instance
easymock_static_call_instance_of_em_snprintf;

static easymock_call_instance*
easymock_static_ptr_call_instance_of_em_snprintf = NULL;

static easymock_params_of_em_snprintf
easymock_static_params_expected_of_em_snprintf;

static easymock_params_of_em_snprintf
easymock_static_params_received_of_em_snprintf;

static easymock_result_of_em_snprintf
easymock_static_result_of_em_snprintf;

static easymock_call_instance* easymock_new_static_em_snprintf()
{
    easymock_call_instance* ci = NULL;
    memset(&easymock_static_call_instance_of_em_snprintf, 0,
           sizeof(easymock_static_call_instance_of_em_snprintf));
    memset(&easymock_static_params_expected_of_em_snprintf, 0,
           sizeof(easymock_static_params_expected_of_em_snprintf));
    memset(&easymock_static_params_received_of_em_snprintf, 0,
           sizeof(easymock_static_params_received_of_em_snprintf));
    ci = &easymock_static_call_instance_of_em_snprintf;
    ci->params_expected =
        &easymock_static_params_expected_of_em_snprintf;
    ci->params_received =
        &easymock_static_params_received_of_em_snprintf;
    ci->result =
        &easymock_static_result_of_em_snprintf;
    ci->func = &easymock_meta_func_of_em_snprintf;
    return ci;
}

static easymock_call_instance* easymock_get_static_em_snprintf()
{
    return easymock_static_ptr_call_instance_of_em_snprintf;
}

static easymock_call_instance* easymock_new_em_snprintf()
{
    easymock_call_instance* ci = NULL;
    if (easymock_is_started()) {
        ci = easymock_call_instance_create();
        ci->params_expected =
            easymock_create_params_of_em_snprintf();
        ci->params_received =
            easymock_create_params_of_em_snprintf();
        ci->result =
            easymock_create_result_of_em_snprintf();
        ci->func = &easymock_meta_func_of_em_snprintf;
        easymock_call_instance_push(ci);
    } else {
        ci = easymock_new_static_em_snprintf();
        easymock_static_ptr_call_instance_of_em_snprintf = ci;
    }
    return ci;
}

void easymock_ignore_and_return_em_snprintf(
    easymock_return_type_of_em_snprintf _em_return_value)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_IGNORE;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    easymock_assign_result_of_em_snprintf(
        _em_ci->result, _em_return_value);
}

void easymock_ignore_and_callback_em_snprintf(
    easymock_fn_callback_em_snprintf _em_fn_callback,
    void* _em_arg_cb)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_IGNORE;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_callback = _em_arg_cb;
}

void easymock_match_va_and_return_em_snprintf(
    easymock_return_type_of_em_snprintf _em_return_value,
    char* str,
    size_t size,
    const char* format,
    ...)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_MATCH;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    easymock_assign_params_of_em_snprintf(
        _em_ci->params_expected,
        str,
        size,
        format);
    easymock_assign_result_of_em_snprintf(
        _em_ci->result, _em_return_value);
    {
        easymock_params_of_em_snprintf* _em_p =
            (easymock_params_of_em_snprintf*)
            _em_ci->params_expected;
        va_start(_em_p->_em_va_list, format);
        {
            int _em_len = 0;
            _em_len = vsnprintf(NULL, 0,
                                format, _em_p->_em_va_list);
            _em_p->_em_va_formatted = malloc(_em_len + 1);
            vsnprintf(_em_p->_em_va_formatted, _em_len + 1,
                      format, _em_p->_em_va_list);
        }
    }
}

void easymock_match_va_and_callback_em_snprintf(
    easymock_fn_callback_em_snprintf _em_fn_callback,
    void* _em_arg_cb,
    char* str,
    size_t size,
    const char* format,
    ...)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_MATCH;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    easymock_assign_params_of_em_snprintf(
        _em_ci->params_expected,
        str,
        size,
        format);
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_callback = _em_arg_cb;
    {
        easymock_params_of_em_snprintf* _em_p =
            (easymock_params_of_em_snprintf*)
            _em_ci->params_expected;
        va_start(_em_p->_em_va_list, format);
        {
            int _em_len = 0;
            _em_len = vsnprintf(NULL, 0,
                                format, _em_p->_em_va_list);
            _em_p->_em_va_formatted = malloc(_em_len + 1);
            vsnprintf(_em_p->_em_va_formatted, _em_len + 1,
                      format, _em_p->_em_va_list);
        }
    }
}

void easymock_check_and_return_em_snprintf(
    easymock_fn_check_em_snprintf _em_fn_check,
    void* _em_arg_ch,
    easymock_return_type_of_em_snprintf _em_return_value)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_CHECK;
    _em_ci->act_mode = EASYMOCK_ACT_RETURN;
    _em_ci->fn_check = _em_fn_check;
    _em_ci->arg_check = _em_arg_ch;
    easymock_assign_result_of_em_snprintf(
        _em_ci->result, _em_return_value);
}

void easymock_check_and_callback_em_snprintf(
    easymock_fn_check_em_snprintf _em_fn_check,
    void* _em_arg_ch,
    easymock_fn_callback_em_snprintf _em_fn_callback,
    void* _em_arg_cb)
{
    easymock_call_instance* _em_ci = easymock_new_em_snprintf();
    _em_ci->prm_mode = EASYMOCK_PRM_CHECK;
    _em_ci->act_mode = EASYMOCK_ACT_CALLBACK;
    _em_ci->fn_check = _em_fn_check;
    _em_ci->fn_callback = _em_fn_callback;
    _em_ci->arg_check = _em_arg_ch;
    _em_ci->arg_callback = _em_arg_cb;
}

int em_snprintf(
    char* str,
    size_t size,
    const char* format,
    ...)
{
    static char _em_sparams[EASYMOCK_MSG_ERROR_LENGTH_MAX] =
        "    (no params)\n";

    easymock_call_instance* _em_ci = NULL;
    int _em_is_unexpected = 0;
    int _em_is_seq_call = 0;

    // 1) try to get a sequence-configured call instance
    _em_ci = easymock_call_instance_pop("em_snprintf");
    if (_em_ci) {
        easymock_nb_seq_calls_inc();
        _em_is_seq_call = 1;
    } else {
        // 2) try to get a static-configured call instance
        _em_ci = easymock_get_static_em_snprintf();
        if (_em_ci) {
            easymock_nb_stc_calls_inc();
        } else {
            // 3) get a dummy all-zero static call instance
            _em_ci = easymock_new_static_em_snprintf();
            _em_is_unexpected = easymock_is_started();
        }
    }
    assert(_em_ci);

    easymock_assign_params_of_em_snprintf(
        _em_ci->params_received,
        str,
        size,
        format);
    {
        easymock_params_of_em_snprintf* _em_p =
            (easymock_params_of_em_snprintf*)
            _em_ci->params_received;
        va_start(_em_p->_em_va_list, format);
        {
            int _em_len = 0;
            _em_len = vsnprintf(NULL, 0,
                                format, _em_p->_em_va_list);
            _em_p->_em_va_formatted = malloc(_em_len + 1);
            vsnprintf(_em_p->_em_va_formatted, _em_len + 1,
                      format, _em_p->_em_va_list);
        }
    }

    if (_em_is_unexpected) {
        // print the received params
        easymock_call_instance_print_params(
            _em_ci, _em_sparams, sizeof(_em_sparams));

        easymock_error(
            "%s: Called - UNEXPECTED!\n%s", "em_snprintf",
            _em_sparams);
    } else {
        if (_em_is_seq_call) {
            easymock_log("%s: Called - OK\n", "em_snprintf");
        }

        // === match params
        if (_em_ci->prm_mode == EASYMOCK_PRM_MATCH) {
            easymock_call_instance_match_params(_em_ci);
        }
        // === check params
        else if (_em_ci->prm_mode == EASYMOCK_PRM_CHECK) {
            assert(_em_ci->fn_check);
            int _em_rc = ((easymock_fn_check_em_snprintf)_em_ci->fn_check)(
                (easymock_params_of_em_snprintf*)_em_ci->params_received,
                _em_ci->arg_check);
            easymock_call_instance_print_params(
                _em_ci, _em_sparams, sizeof(_em_sparams));
            if (_em_rc == 0) {
                easymock_log(
                    "%s: Check - OK\n%s",
                    "em_snprintf", _em_sparams);
            } else {
                easymock_error(
                    "%s: Check - FAILED!\n%s",
                    "em_snprintf", _em_sparams);
            }
        }
        // === call the provided callback
        if (_em_ci->act_mode == EASYMOCK_ACT_CALLBACK) {
            assert(_em_ci->fn_callback);
            return ((easymock_fn_callback_em_snprintf)
                _em_ci->fn_callback)(
                    (easymock_params_of_em_snprintf*)
                    _em_ci->params_received,
                    _em_ci->arg_callback);
        }
    }
    // === return the result
    return ((easymock_result_of_em_snprintf*)
            _em_ci->result)->return_value;
}
