//! Generated by easymock

#ifndef EASYMOCK_EM_HEADER_3_H
#define EASYMOCK_EM_HEADER_3_H

#include <easymock.h>
#include "em_header_3.h"

//!
//! Mock for em_func_inside_header_3_b
//!

easymock_func* easymock_meta_of_em_func_inside_header_3_b(void);

typedef struct easymock_params_of_em_func_inside_header_3_b_tag {
    int x;
} easymock_params_of_em_func_inside_header_3_b;

typedef int easymock_return_type_of_em_func_inside_header_3_b;

typedef struct easymock_result_of_em_func_inside_header_3_b_tag {
    easymock_return_type_of_em_func_inside_header_3_b return_value;
} easymock_result_of_em_func_inside_header_3_b;

typedef int (*easymock_fn_callback_em_func_inside_header_3_b)(
    const easymock_params_of_em_func_inside_header_3_b*,
    void*);

typedef int (*easymock_fn_check_em_func_inside_header_3_b)(
    const easymock_params_of_em_func_inside_header_3_b*,
    void*);

void easymock_ignore_and_return_em_func_inside_header_3_b(
    easymock_return_type_of_em_func_inside_header_3_b _em_return_value);

void easymock_ignore_and_callback_em_func_inside_header_3_b(
    easymock_fn_callback_em_func_inside_header_3_b _em_fn_callback,
    void* _em_arg_cb);

void easymock_match_and_return_em_func_inside_header_3_b(
    int x,
    easymock_return_type_of_em_func_inside_header_3_b _em_return_value);

void easymock_match_and_callback_em_func_inside_header_3_b(
    int x,
    easymock_fn_callback_em_func_inside_header_3_b _em_fn_callback,
    void* _em_arg_cb);

void easymock_check_and_return_em_func_inside_header_3_b(
    easymock_fn_check_em_func_inside_header_3_b _em_fn_check,
    void* _em_arg_ch,
    easymock_return_type_of_em_func_inside_header_3_b _em_return_value);

void easymock_check_and_callback_em_func_inside_header_3_b(
    easymock_fn_check_em_func_inside_header_3_b _em_fn_check,
    void* _em_arg_ch,
    easymock_fn_callback_em_func_inside_header_3_b _em_fn_callback,
    void* _em_arg_cb);

/* Original function declaration:
int em_func_inside_header_3_b(
    int x);
*/

//!
//! Mock for em_func_inside_header_3_a
//!

easymock_func* easymock_meta_of_em_func_inside_header_3_a(void);

typedef struct easymock_params_of_em_func_inside_header_3_a_tag {
    int x;
} easymock_params_of_em_func_inside_header_3_a;

typedef int easymock_return_type_of_em_func_inside_header_3_a;

typedef struct easymock_result_of_em_func_inside_header_3_a_tag {
    easymock_return_type_of_em_func_inside_header_3_a return_value;
} easymock_result_of_em_func_inside_header_3_a;

typedef int (*easymock_fn_callback_em_func_inside_header_3_a)(
    const easymock_params_of_em_func_inside_header_3_a*,
    void*);

typedef int (*easymock_fn_check_em_func_inside_header_3_a)(
    const easymock_params_of_em_func_inside_header_3_a*,
    void*);

void easymock_ignore_and_return_em_func_inside_header_3_a(
    easymock_return_type_of_em_func_inside_header_3_a _em_return_value);

void easymock_ignore_and_callback_em_func_inside_header_3_a(
    easymock_fn_callback_em_func_inside_header_3_a _em_fn_callback,
    void* _em_arg_cb);

void easymock_match_and_return_em_func_inside_header_3_a(
    int x,
    easymock_return_type_of_em_func_inside_header_3_a _em_return_value);

void easymock_match_and_callback_em_func_inside_header_3_a(
    int x,
    easymock_fn_callback_em_func_inside_header_3_a _em_fn_callback,
    void* _em_arg_cb);

void easymock_check_and_return_em_func_inside_header_3_a(
    easymock_fn_check_em_func_inside_header_3_a _em_fn_check,
    void* _em_arg_ch,
    easymock_return_type_of_em_func_inside_header_3_a _em_return_value);

void easymock_check_and_callback_em_func_inside_header_3_a(
    easymock_fn_check_em_func_inside_header_3_a _em_fn_check,
    void* _em_arg_ch,
    easymock_fn_callback_em_func_inside_header_3_a _em_fn_callback,
    void* _em_arg_cb);

/* Original function declaration:
int em_func_inside_header_3_a(
    int x);
*/

//!
//! Mock for em_func_inside_header_3
//!

easymock_func* easymock_meta_of_em_func_inside_header_3(void);

typedef struct easymock_params_of_em_func_inside_header_3_tag {
    int x;
} easymock_params_of_em_func_inside_header_3;

typedef int easymock_return_type_of_em_func_inside_header_3;

typedef struct easymock_result_of_em_func_inside_header_3_tag {
    easymock_return_type_of_em_func_inside_header_3 return_value;
} easymock_result_of_em_func_inside_header_3;

typedef int (*easymock_fn_callback_em_func_inside_header_3)(
    const easymock_params_of_em_func_inside_header_3*,
    void*);

typedef int (*easymock_fn_check_em_func_inside_header_3)(
    const easymock_params_of_em_func_inside_header_3*,
    void*);

void easymock_ignore_and_return_em_func_inside_header_3(
    easymock_return_type_of_em_func_inside_header_3 _em_return_value);

void easymock_ignore_and_callback_em_func_inside_header_3(
    easymock_fn_callback_em_func_inside_header_3 _em_fn_callback,
    void* _em_arg_cb);

void easymock_match_and_return_em_func_inside_header_3(
    int x,
    easymock_return_type_of_em_func_inside_header_3 _em_return_value);

void easymock_match_and_callback_em_func_inside_header_3(
    int x,
    easymock_fn_callback_em_func_inside_header_3 _em_fn_callback,
    void* _em_arg_cb);

void easymock_check_and_return_em_func_inside_header_3(
    easymock_fn_check_em_func_inside_header_3 _em_fn_check,
    void* _em_arg_ch,
    easymock_return_type_of_em_func_inside_header_3 _em_return_value);

void easymock_check_and_callback_em_func_inside_header_3(
    easymock_fn_check_em_func_inside_header_3 _em_fn_check,
    void* _em_arg_ch,
    easymock_fn_callback_em_func_inside_header_3 _em_fn_callback,
    void* _em_arg_cb);

/* Original function declaration:
int em_func_inside_header_3(
    int x);
*/

#endif
